import { Poppins } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { Metadata } from 'next'; 
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Providers from './providers';


const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// Add Poppins font with specified weight and subsets
const poppins = Poppins({
  weight: ['100', '400', '600', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata: Metadata = { // Type defined here
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <Providers>
        <Navbar />
        {children}
        <Footer />
        </Providers>
      </body>
    </html>
  );
}

