import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    title: "Mens Must-Haves",
    image: ["/mens/5.jpg"],
    slug: "black-hoodie",
    price: 150,
    discount: 0,
    category: "mens",
    description: `"A high-quality hoodie jacket is warm, comfortable, and durable,
              made from premium fabrics like soft cotton or fleece. With sturdy
              stitching, reliable zippers, and a modern design, it offers both
              style and functionality. Perfect for casual wear or layering, it&apos;s
              a versatile wardrobe essential."`,
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },

  {
    id: 2,
    title: "Mens Must-Haves",
    image: ["/mens/4.jpg"],
    slug: "black-jacket",
    price: 250,
    discount: 0,
    category: "mens",
    description: `"A high-quality jacket is warm, comfortable, and durable,
                  made from premium fabrics like soft cotton or fleece. With sturdy
                  stitching, reliable zippers, and a modern design, it offers both
                  style and functionality. Perfect for casual wear or layering, it&apos;s
                  a versatile wardrobe essential."`,
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
  },
  {
    id: 3,
    title: "Mens Must-Haves",
    image: ["/mens/3.jpg"],
    slug: "hoodie-blue-white",
    price: 200,
    discount: 0,
    category: "mens",
    description: `"A high-quality hoodie is warm, comfortable, and durable,
          made from premium fabrics like soft cotton or fleece. With sturdy
          stitching, reliable zippers, and a modern design, it offers both
          style and functionality. Perfect for casual wear or layering, it&apos;s
          a versatile wardrobe essential."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 4,
    title: "Mens Must-Haves",
    image: ["/mens/2.jpg"],
    slug: "brown-hoodie",
    price: 250,
    discount: 0,
    category: "mens",
    description: `"A high-quality hoodie jacket is warm, comfortable, and durable,
          made from premium fabrics like soft cotton or fleece. With sturdy
          stitching, reliable zippers, and a modern design, it offers both
          style and functionality. Perfect for casual wear or layering, it&apos;s
          a versatile wardrobe essential."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 5,
    title: "Mens Must-Haves",
    image: ["/mens/1.jpg"],
    slug: "black-white-uppar",
    price: 290,
    discount: 0,
    category: "mens",
    description: `"A high-quality hoodie upper is warm, comfortable, and durable,
          made from premium fabrics like soft cotton or fleece. With sturdy
          stitching, reliable zippers, and a modern design, it offers both
          style and functionality. Perfect for casual wear or layering, it&apos;s
          a versatile wardrobe essential."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 6,
    title: "Mens Must-Haves",
    image: ["/mens/5.jpg"],
    slug: "black-hoodie-upper",
    price: 150,
    discount: 0,
    category: "mens",
    description: `"A high-quality hoodie jacket is warm, comfortable, and durable,
          made from premium fabrics like soft cotton or fleece. With sturdy
          stitching, reliable zippers, and a modern design, it offers both
          style and functionality. Perfect for casual wear or layering, it&apos;s
          a versatile wardrobe essential."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 7,
    title: "Toddler Baby Boy Outfit",
    image: ["/kids/kid5.jpg"],
    slug: "brown-suit",
    price: 250,
    discount: 0,
    category: "kids",
    description: `"Soft and comfortable kids' dress made from high-quality, breathable fabric. Designed for all-day wear with vibrant colors and adorable patterns, perfect for casual outings or special occasions."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 8,
    title: "Toddler Baby Boy Outfit",
    image: ["/kids/kid6.jpg"],
    slug: "black-orange-stylish-suit",
    price: 150,
    discount: 0,
    category: "kids",
    description: `"Soft and comfortable kids' dress made from high-quality, breathable fabric. Designed for all-day wear with vibrant colors and adorable patterns, perfect for casual outings or special occasions."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 9,
    title: "Toddler Baby Boy Outfit",
    image: ["/kids/kid4.jpg"],
    slug: "blue-white-warm-suit",
    price: 200,
    discount: 0,
    category: "kids",
    description: `"Soft and comfortable kids' dress made from high-quality, breathable fabric. Designed for all-day wear with vibrant colors and adorable patterns, perfect for casual outings or special occasions."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 10,
    title: "Toddler Baby Boy Outfit",
    image: ["/kids/kid3.jpg"],
    slug: "blue-stylish-three-piece",
    price: 350,
    discount: 0,
    category: "kids",
    description: `"Soft and comfortable kids' dress made from high-quality, breathable fabric. Designed for all-day wear with vibrant colors and adorable patterns, perfect for casual outings or special occasions."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 11,
    title: "Toddler Baby Boy Outfit",
    image: ["/kids/kid2.jpg"],
    slug: "stylish-three-piece",
    price: 350,
    discount: 0,
    category: "kids",
    description: `"Soft and comfortable kids' dress made from high-quality, breathable fabric. Designed for all-day wear with vibrant colors and adorable patterns, perfect for casual outings or special occasions."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 12,
    title: "Toddler Baby Boy Outfit",
    image: ["/kids/kid1.jpg"],
    slug: "fancy-wear-stylish-suit",
    price: 250,
    discount: 0,
    category: "kids",
    description: `"Soft and comfortable kids' dress made from high-quality, breathable fabric. Designed for all-day wear with vibrant colors and adorable patterns, perfect for casual outings or special occasions."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 13,
    title: "Women's Heaven",
    image: ["/women/women1.webp"],
    slug: "brown-hooi",
    price: 250,
    discount: 0,
    category: "womens",
    description: `"Cold days, hot style! Discover our warm and stylish uppers for women, where comfort meets timeless design."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 14,
    title: "Women's Heaven",
    image: ["/women/women2.webp"],
    slug: "elegent-upper",
    price: 200,
    discount: 0,
    category: "womens",
    description: `"Cold days, hot style! Discover our warm and stylish uppers for women, where comfort meets timeless design."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 15,
    title: "Women's Heaven",
    image: ["/women/women3.webp"],
    slug: "white-fancy",
    price: 350,
    discount: 0,
    category: "womens",
    description: `"Cold days, hot style! Discover our warm and stylish uppers for women, where comfort meets timeless design."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 16,
    title: "Women's Heaven",
    image: ["/women/women4.webp"],
    slug: "black-elegent",
    price: 200,
    discount: 0,
    category: "womens",
    description: `"Cold days, hot style! Discover our warm and stylish uppers for women, where comfort meets timeless design."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 17,
    title: "Women's Heaven",
    image: ["/women/women5.webp"],
    slug: "black-top",
    price: 250,
    discount: 0,
    category: "womens",
    description: `"Cold days, hot style! Discover our warm and stylish uppers for women, where comfort meets timeless design."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
{
    id: 18,
    title: "Women's Heaven",
    image: ["/women/women6.webp"],
    slug: "stylish-cute-warm-top",
    price: 350,
    discount: 0,
    category: "womens",
    description: `"Cold days, hot style! Discover our warm and stylish uppers for women, where comfort meets timeless design."`,
    size: ["S","M","L","XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,      
},
];
